[package]
name = "ss_cli"
version = "0.1.0"
authors = ["Lasse Seivaag <lasse_0407@hotmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90", features = ["derive"] }
serde_json = "1.0"